version: '3'



services:

  singular-dag:

    image: singular-dag:latest


    environment:
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/airflow/dags
    volumes:
      - ./airflow:/opt/airflow/airflow
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./db:/opt/airflow/db




    ports:

      - "8080:8080"



    command: airflow standalone